CREATE TABLE IF NOT EXISTS company(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,contactname TEXT,contactemail TEXT);
INSERT or IGNORE INTO company VALUES(1,"Yesh","Yesh","Yesh");
CREATE TABLE IF NOT EXISTS task(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT , companyId INTEGER,date Date,time TIME);
-- CREATE TABLE IF NOT EXISTS product(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT, creatorId INTEGER);